using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SyntaxAnalyser
{
    class Constants
    {
        public static string END = "END",
            PROGRAM = "PROGRAM",
            IDENTIFIER = "IDENTIFIER",
            SEMICOLON = "SEMICOLON",
            PARANTHESIS_L = "PARENTHESIS_L",
            PARANTHESIS_R = "PARENTHESIS_R",
            BEGIN = "BEGIN",
            IF = "IF",
            WHILE = "WHILE",
            ASSIGN_OP = "ASSIGN_OP",
            MOD = "MOD",
            DO = "DO",
            THEN = "THEN",
            ELSE = "ELSE",
            READ = "READ",
            WRITE = "WRITE",
            LEFT_OP = "LEFT_OP",
            RIGHT_OP = "RIGHT_OP",
            COLON = "COLON",
            BRACKET_L = "BRACKET_L",
            BRACKET_R = "BRACKET_R",
            PLUS = "PLUS",
            MINUS = "MINUS",
            CONST_INT = "CONST",
            VARIABLE = "VARIABLE",
            COMMA = "COMMA",
            INTARRAY = "INTARRAY",
            INT = "INT",
            EQ_OP = "EQ_OP",
            NE_OP = "NE_OP",
            CHEVRON_L = "CHEVRON_L",
            CHEVRON_R = "CHEVRON_R",
            LE_OP = "LE_OP",
            GE_OP = "GE_OP",
            OR = "OR",
            STAR = "STAR",
            DIV = "SLASH",
            POINT = "POINT",
            VAR = "VAR",
            ENDVAR = "ENDVAR",
            MATH = "MATH",
            BOOL = "BOOL",
            STREAM_R = "STREAM_R",
            STREAM_L = "STREAM_L",
            MORE_OP = "MORE_OP",
            LESS_OP = "LESS_OP",
            ENDIF = "ENDIF",
            ENDWHILE = "ENDWHILE",
            MULT = "MULT",
            INTEGER = "INTEGER",
            BLOCK_STATMENT = "BlockStatment",
            PROGRAM_STATMENT = "ProgramStatment",
            VARIBLE_DECLARATION_RAPT = "VaribleDeclarationPart",
            VARIBLE_DECLARATION = "VaribleDeclaration",
            TYPE_STATMENT = "TypeStatment",
            INTEGER_TYPE_STATMENT = "IntegerType",
            ARRAY_TYPE_STATMENT = "ArrayType",
            STATMENT_PART = "StatmentPart",
            VARIBLE_STATMENT = "VaribleStatment",
            ASSIGNMENT_STATMENT = "AssignmentStatment",
            ARRAY_ASSIGNMENT = "ArrayAssignment",
            READ_STATMENT = "ReadStatment",
            WRITE_STATMENT = "WriteStatment",
            STATMENT = "Statment",
            IF_STATMENT = "IfStatment",
            WHILE_STATMENT = "WhileStatment",
            BOOL_STATMENT = "BoolStatment",
            BOOL_EXPRESSION = "BoolExpression",
            MATH_STATMENT = "MathStatment",
            MATH_EXPRESSION = "MathExpression",
            FACTOR = "Factor",
            MATH_OPERATOR = "MathOperator",
            RELATIONAL_OPERATOR = "RelationalOperator",
            ENDPROGRAM = "ENDPROGRAM",
            TO = "TO",
            FROM = "FROM";
    }
}
